name: validate-schema
on: [push, pull_request]
jobs:
  ajv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: ./scripts/dev-install.sh
      - run: npm run validate
